# Generated by Django 4.2.9 on 2024-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(default=1231)),
                ('hours', models.IntegerField()),
                ('projects', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('READY', 'Ready'), ('NOT READY', 'Not ready')], max_length=15)),
            ],
            options={
                'verbose_name': 'Проекты',
            },
        ),
    ]
