# Generated by Django 4.2.9 on 2024-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employee_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
