# Generated by Django 3.2.25 on 2024-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='project',
            name='eemployee_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
