# Generated by Django 3.2.25 on 2024-05-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20240519_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='eemployee_id',
            new_name='employee_id',
        ),
    ]
