# Generated by Django 3.2.25 on 2024-05-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_comment'),
        ('projects', '0006_alter_project_comment'),
    ]

    operations = [
    ]
