# Generated by Django 5.0.6 on 2024-06-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='label',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
