# Generated by Django 4.2.9 on 2024-05-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projects',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
