# Generated by Django 4.2.9 on 2024-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_alter_projects_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='employee_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
