# Generated by Django 3.2.25 on 2024-05-20 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generatedReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=datetime.datetime(2024, 5, 20, 16, 27, 42, 721939), max_length=256, null=True)),
                ('type', models.CharField(max_length=256, null=True)),
                ('date_range', models.CharField(max_length=256, null=True)),
                ('download_link', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'generatedReports',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=248, null=True)),
                ('type', models.CharField(default='None', max_length=256)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reports',
            },
        ),
    ]
