# Generated by Django 3.2.25 on 2024-05-20 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreports',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 5, 20, 16, 28, 0, 365713), max_length=256, null=True),
        ),
    ]
