# Generated by Django 3.2.25 on 2024-05-20 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_generatedreports_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreports',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 5, 20, 16, 34, 39, 967491), max_length=256, null=True),
        ),
    ]
