# Generated by Django 3.2.25 on 2024-05-20 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_generatedreports_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreports',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 5, 20, 17, 19, 33, 153025), max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 17, 19, 33, 152404)),
        ),
    ]
