# Generated by Django 5.0.6 on 2024-06-05 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20240520_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreports',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 6, 5, 10, 51, 1, 781415), max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 10, 51, 1, 781204)),
        ),
    ]
